version: "3"

services:
  app:
    image: node
    command: bash -c "cd /usr/app && npm run bootstrap"
    volumes:
      - .:/usr/app
    ports:
      - "8999:8999"
    environment:
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000/?--user-data-dir=./tmp/translateer-data"
      PAGE_COUNT: "5"
    depends_on:
      - browserless
  build:
    commands:
      - ./render-build.sh

  browserless:
    image: browserless/chrome
    restart: always
    environment:
      CONNECTION_TIMEOUT: "-1"

